* smart-httpd
A user-friendly web framework for Gerbil Scheme

** Installation
Add to your =.gerbil/pkg= directory:
#+begin_src shell
git clone https://github.com/luciusmagn/smart-httpd .gerbil/pkg/smart-httpd
#+end_src

** Quick Start
#+begin_src scheme
(import :smart-httpd)

;; Define a handler with type-safe parameters
(define greet-handler
 (handler ((name :>string)) <- (body :>)
   (string-append "Hello, " name "!")))

;; Define routes
(define routes
 (list
   (get "/greet/:name" greet-handler)))

;; Start server
(run-server routes port: 8080)
#+end_src

** Handlers
Handlers are defined using the =handler= macro which provides type-safe parameter extraction:

#+begin_src scheme
;; body conversion can be omitted with :>
(define echo-handler
 (handler () <- (body :>)
   body))

;; JSON body handling
(define json-handler
 (handler () <- (body :>json)
   (let ((name (hash-ref body 'name))
         (age  (hash-ref body 'age)))
     (string-append "Hello " name ", you are " (number->string age)))))

;; Form data handling
(define form-handler
 (handler () <- (body :>form)
   (let ((username (hash-ref body 'username))
         (password (hash-ref body 'password)))
     (string-append "Login attempt by: " username))))

;; params are defined like this
;; this request ignores the body
(define add-handler
 (handler ((a :>number) (b :>number)) <- (_ :>)
   (number->string (+ a b))))
#+end_src

Available type converters:
- =:>= - identity (same as :>string)
- =:>string= - identity
- =:>number= - string->number
- =:>symbol= - string->symbol
- =:>keyword= - string->keyword
- =:>uuid= - string->uuid
- =:>json= - parse JSON body into hash table
- =:>form= - parse x-www-form-urlencoded body into hash table

Handlers can return:
- string - responds with 200 and the string
- file-path - serves the file
- (status . body) - responds with status code and body
- (status headers body) - responds with status, headers and body
- rejection - continues to next matching handler or error handler

** Routes
Routes are defined using HTTP method helpers:

#+begin_src scheme
(define routes
 (list
   (get    "/users/:id" get-user-handler)
   (post   "/users"     create-user-handler)
   (put    "/users/:id" update-user-handler)
   (patch  "/users/:id" patch-user-handler)
   (delete "/users/:id" delete-user-handler)))
#+end_src

The list can be infinitely nested and collect routes from across your app:

#+begin_src scheme
(define user-routes
 (list
   (get  "/users"     list-users)
   (post "/users"     create-user)))

(define post-routes
 (list
   (get  "/posts"     list-posts)
   (post "/posts"     create-post)))

(define routes
 (list
   user-routes
   post-routes))
#+end_src

** Static Files
To serve static files, provide a custom handler to the router:

#+begin_src scheme
(define my-static-handler
 (lambda (path)
   (file-path (string-append "./public/" path))))

(run-server routes
 port: 8080
 static: my-static-handler)
#+end_src

** Error Handling
Custom error handling can be provided:

#+begin_src scheme
(define my-error-handler
 (lambda (rejection)
   (format "Error: ~a - ~a"
           (rejection-type rejection)
           (rejection-msg rejection))))

(run-server routes
 port: 8080
 recovery: my-error-handler)
#+end_src

** HTML Templates with SHSX
smart-httpd works great with SHSX for HTML templating:

#+begin_src scheme
(import :smart-httpd
       :shsx/lib)

(define template-handler
 (handler ((name :>string)) <- (_ :>)
   (render-html
    (shsx
     (html:
      (head:
       (title: "Greeting"))
      (body:
       (h1: "Hello, " ,name "!")
       (p: "Welcome to our site")
       ,(@when (string=? name "admin")
          (div: class: "admin-panel"
                (p: "Admin controls here")))))))))

(define routes
 (list
   (get "/greet/:name" template-handler)))

(run-server routes port: 8080)
#+end_src

SHSX provides a clean syntax for generating HTML with full Scheme integration.
See the [[https://github.com/luciusmagn/shsx][SHSX documentation]] for more details about templating features.

** License
Fair License

Copyright (c) 2025 Lukáš Hozda

Usage of the works is permitted provided that this instrument is retained with the works, so that any entity that uses the works is notified of this instrument.

DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.
#+end_src
